"""KiCad 9 embedded-file format invariants (Phase 1 of the additive intent).

The on-disk contract these tests freeze (verified against the KiCad 9 source
and real KiCad-authored files on 2026-06-11):
  zstd level 15 -> base64 wrapped at 76 chars in |...| -> checksum =
  KiCad's NON-standard MurmurHash3-128 of the raw bytes, seed 0xABBA2345,
  rendered as 32 uppercase hex chars.
"""

from __future__ import annotations

import base64

import pytest
import zstandard

from app.kicad_embed import (
    KICAD_EMBED_SEED,
    KICAD_ZSTD_LEVEL,
    MIME_BASE64_LENGTH,
    _node_span,
    bake_step_into_kicad_mod,
    checksum_matches,
    decode_payload,
    encode_payload,
    find_embedded_files,
    kicad_mmh3_hex,
    replace_embedded_payload,
    scaffold_kicad_mod,
)

# Golden digests generated by the implementation that was validated against
# KiCad ground truth (qa fixtures + 13 real-world footprints, all schemes).
# Input for length n is bytes(range(n)). If any of these change, the bake is
# no longer KiCad-compatible.
MMH3_GOLDENS = [
    (0, "0A8AD5D826E19AE9B0771881583631B3"),
    (1, "C3727014ACDAB51B9B1ACE5901738C9B"),
    (2, "89C1C8F15736A3980840AD1EE95C155D"),
    (3, "0D86AF4F52780DD119DD9546ED6D9C48"),
    (4, "2D26461D340414A0CCE6A263CDBC6B97"),
    (5, "DE0D7F7F6A72C170229D337A39CF08F9"),
    (7, "024D299D9EF2763D05603F0FD750F772"),
    (8, "094BDA706CA9D7613D617E79B9C3D720"),
    (9, "F9E8FB5FA73F9E6B291F19F9FAEFC835"),
    (12, "0FC02384A29118F69FFB8F37551022E3"),
    (15, "0FC02384A29118F69FFB8F37551022E3"),
    (16, "FA03DBB5E3A1C1BAF12D125E128A2FED"),
    (17, "AE4D43D9369D8AD162B817F10D62B375"),
    (31, "0135EB51A8669012E5791EDD9F812277"),
    (32, "AEA970FB8BA5135C00409EF2929F2D87"),
    (100, "DAABA856457D52139B66695C6627A735"),
]


class TestKicadMmh3:
    @pytest.mark.parametrize("length,expected", MMH3_GOLDENS)
    def test_golden_vectors(self, length, expected):
        data = bytes(i & 0xFF for i in range(length))
        assert kicad_mmh3_hex(data) == expected

    def test_format_is_32_uppercase_hex(self):
        digest = kicad_mmh3_hex(b"hello world")
        assert len(digest) == 32
        assert digest == digest.upper()
        int(digest, 16)  # must parse as hex

    def test_seed_constant(self):
        # KiCad's EMBEDDED_FILES::Seed() — include/embedded_files.h
        assert KICAD_EMBED_SEED == 0xABBA2345

    def test_kicad_padding_quirk_is_preserved(self):
        # KiCad's addData() zero-pads the tail to 4 bytes and counts the
        # padding in len: a 12-byte tail pads to 16 -> len&15 == 0 -> the
        # tail bytes never enter the mix. Lengths 12..15 therefore hash
        # identically. This is wrong by murmur3 standards and REQUIRED for
        # KiCad compatibility — a "fixed" implementation must fail here.
        digests = {kicad_mmh3_hex(bytes(range(n))) for n in (12, 13, 14, 15)}
        assert len(digests) == 1

    def test_not_standard_murmur3(self):
        mmh3 = pytest.importorskip("mmh3")
        standard = mmh3.hash_bytes(b"hello world", KICAD_EMBED_SEED, x64arch=True)
        assert standard.hex().upper() != kicad_mmh3_hex(b"hello world")


class TestChecksumSchemes:
    def test_mmh3_scheme_accepted(self):
        raw = b"payload"
        assert checksum_matches(kicad_mmh3_hex(raw), raw)

    def test_legacy_sha256_scheme_accepted(self):
        import hashlib

        raw = b"payload"
        assert checksum_matches(hashlib.sha256(raw).hexdigest(), raw)

    def test_wrong_checksums_rejected(self):
        raw = b"payload"
        assert not checksum_matches("0" * 32, raw)
        assert not checksum_matches("0" * 64, raw)

    def test_case_insensitive_on_read(self):
        raw = b"payload"
        assert checksum_matches(kicad_mmh3_hex(raw).lower(), raw)


class TestPayloadCodec:
    def test_roundtrip(self):
        raw = bytes(range(256)) * 41
        b64, checksum = encode_payload(raw)
        assert decode_payload(b64) == raw
        assert checksum_matches(checksum, raw)

    def test_encode_golden(self):
        # Locks the zstd frame bytes (level 15, content size written): the
        # byte-parity-with-KiCad property depends on this exact framing.
        b64, checksum = encode_payload(b"hello world")
        assert b64 == "KLUv/SALWQAAaGVsbG8gd29ybGQ="
        assert checksum == "3EBD98E281DB799C63EED514E23DF44C"

    def test_zstd_level_constant(self):
        assert KICAD_ZSTD_LEVEL == 15  # ZSTD_compress(..., 15) in KiCad

    def test_encode_is_deterministic(self):
        raw = b"x" * 50_000
        assert encode_payload(raw) == encode_payload(raw)

    def test_frame_carries_content_size(self):
        b64, _ = encode_payload(b"y" * 1000)
        frame = base64.b64decode(b64)
        params = zstandard.get_frame_parameters(frame)
        assert params.content_size == 1000


class TestNodeSpan:
    def test_balanced(self):
        text = "(a (b) (c (d)))"
        assert _node_span(text, 0) == (0, len(text))

    def test_quoted_parens_ignored(self):
        text = '(file (name "weird ) ( name") (type model))'
        assert _node_span(text, 0) == (0, len(text))

    def test_escaped_quote_inside_string(self):
        text = '(name "a\\"b)")(next)'
        assert _node_span(text, 0) == (0, text.index(")(") + 1)

    def test_unbalanced_raises(self):
        with pytest.raises(ValueError):
            _node_span("(a (b)", 0)


class TestScaffold:
    def test_deterministic(self):
        a = scaffold_kicad_mod("part", "part.step", b"ISO-10303-21;data")
        b = scaffold_kicad_mod("part", "part.step", b"ISO-10303-21;data")
        assert a == b

    def test_reextract_identity(self):
        raw = b"ISO-10303-21;" + bytes(range(256)) * 100
        text = scaffold_kicad_mod("part", "part.step", raw)
        entry = find_embedded_files(text)[0]
        assert entry.name == "part.step"
        assert entry.file_type == "model"
        assert decode_payload(entry.data_base64) == raw
        assert checksum_matches(entry.checksum, raw)

    def test_kicad_embed_reference(self):
        text = scaffold_kicad_mod("part", "part.step", b"x")
        assert '"kicad-embed://part.step"' in text

    def test_data_lines_wrap_at_76(self):
        text = scaffold_kicad_mod("part", "part.step", b"z" * 9000)
        entry = find_embedded_files(text)[0]
        interior = text[text.index("|") + 1 : text.rindex("|")]
        for line in interior.splitlines():
            assert len(line.strip().strip("\t")) <= MIME_BASE64_LENGTH
        assert entry.data_base64  # wrapped form still parses

    def test_uses_crlf(self):
        # Matches what KiCad writes on Windows and what the corpus uses.
        text = scaffold_kicad_mod("part", "part.step", b"x")
        assert "\r\n" in text and "\n" in text


class TestReplacePayload:
    def _scaffold(self, payload: bytes) -> str:
        return scaffold_kicad_mod("part", "part.step", payload)

    def test_swap_and_swap_back_is_byte_identity(self):
        a, b = b"ISO A " * 500, b"ISO B " * 700
        text = self._scaffold(a)
        swapped = replace_embedded_payload(text, find_embedded_files(text)[0], b)
        assert decode_payload(find_embedded_files(swapped)[0].data_base64) == b
        back = replace_embedded_payload(swapped, find_embedded_files(swapped)[0], a)
        # Only the data interior and checksum may ever change.
        assert back == text

    def test_deterministic(self):
        text = self._scaffold(b"one")
        e = find_embedded_files(text)[0]
        assert replace_embedded_payload(text, e, b"two") == replace_embedded_payload(
            text, e, b"two"
        )

    def test_checksum_rewritten(self):
        text = self._scaffold(b"one")
        new = replace_embedded_payload(text, find_embedded_files(text)[0], b"two")
        entry = find_embedded_files(new)[0]
        assert entry.checksum == kicad_mmh3_hex(b"two")

    def test_crlf_preserved(self):
        text = self._scaffold(b"one" * 200)
        new = replace_embedded_payload(text, find_embedded_files(text)[0], b"two" * 300)
        assert "\n" not in new.replace("\r\n", "")

    def test_lf_file_stays_lf(self):
        text = self._scaffold(b"one" * 200).replace("\r\n", "\n")
        new = replace_embedded_payload(text, find_embedded_files(text)[0], b"two" * 300)
        assert "\r" not in new

    def test_missing_checksum_raises(self):
        import re

        text = re.sub(r'\(checksum "[0-9A-F]+"\)', "", self._scaffold(b"one"))
        with pytest.raises(ValueError):
            replace_embedded_payload(text, find_embedded_files(text)[0], b"two")


class TestBakeFile:
    def test_bake_writes_and_preserves_source(self, tmp_path):
        src = tmp_path / "part.kicad_mod"
        with open(src, "w", encoding="utf-8", newline="") as fh:
            fh.write(scaffold_kicad_mod("part", "part.step", b"old payload"))
        before = src.read_bytes()
        out = tmp_path / "part_conditioned.kicad_mod"
        bake_step_into_kicad_mod(str(src), b"new payload", str(out))
        assert src.read_bytes() == before  # opened sources are never modified
        with open(out, encoding="utf-8", newline="") as fh:
            text = fh.read()
        assert decode_payload(find_embedded_files(text)[0].data_base64) == b"new payload"

    def test_wrong_model_name_raises(self, tmp_path):
        src = tmp_path / "part.kicad_mod"
        with open(src, "w", encoding="utf-8", newline="") as fh:
            fh.write(scaffold_kicad_mod("part", "part.step", b"old"))
        with pytest.raises(ValueError):
            bake_step_into_kicad_mod(
                str(src), b"new", str(tmp_path / "o.kicad_mod"), name="other.step"
            )
