"""Friendly Python API for Geometer native geometry operations."""

from ._api import (
    GeometerBatchConfig,
    GeometerBatchResult,
    GeometerBatchRunner,
    executable_path,
    hlr_projection_json,
    model_bounds,
    model_bounds_json,
    model_hlr_projection_json,
    model_to_glb,
    planar_batch_solve,
    planar_batch_solve_json,
    planar_step,
    project_model_hlr,
    project_step_hlr,
    run_batch,
    step_to_glb,
    version,
    write_planar_step,
)
from ._errors import GeometerError
from ._types import (
    HlrOptions,
    HlrProjectionResult,
    ModelBoundsResult,
    PlanarBatchSolveJob,
    PlanarBatchSolveResult,
    PlanarPoint,
    PlanarRegion,
    PlanarRing,
    ProjectionView,
    Version,
)

__all__ = [
    "GeometerError",
    "GeometerBatchConfig",
    "GeometerBatchResult",
    "GeometerBatchRunner",
    "HlrOptions",
    "HlrProjectionResult",
    "ModelBoundsResult",
    "PlanarBatchSolveJob",
    "PlanarBatchSolveResult",
    "PlanarPoint",
    "PlanarRegion",
    "PlanarRing",
    "ProjectionView",
    "Version",
    "executable_path",
    "hlr_projection_json",
    "model_bounds",
    "model_bounds_json",
    "model_hlr_projection_json",
    "model_to_glb",
    "planar_batch_solve",
    "planar_batch_solve_json",
    "planar_step",
    "project_model_hlr",
    "project_step_hlr",
    "run_batch",
    "step_to_glb",
    "version",
    "write_planar_step",
]
