"""Friendly Python API for Geometer native geometry operations."""

from ._api import (
    GeometerBatchConfig,
    GeometerBatchResult,
    GeometerBatchRunner,
    executable_path,
    hlr_projection_json,
    model_bounds,
    model_bounds_json,
    model_hlr_projection_json,
    model_to_glb,
    planar_batch_solve,
    planar_batch_solve_json,
    planar_step,
    project_model_hlr,
    project_step_hlr,
    run_batch,
    step_to_glb,
    version,
    write_planar_step,
)
from ._errors import GeometerError
from ._analytic_packet_a0 import (
    AnalyticPacketError,
    decode_analytic_planar_boolean_batch_result_a0_packet,
    encode_analytic_planar_boolean_batch_request_a0_packet,
)
from ._generated.contracts.models import (
    AnalyticPlanarBooleanBatchRequestA0,
    AnalyticPlanarBooleanBatchResultA0,
    AnalyticPlanarBooleanJob,
    AnalyticPlanarBooleanStage,
    AnalyticPlanarOperand,
    AnnulusOperand,
    ArcDirection,
    AuthoredCircularArcByRadiusSegment,
    AuthoredCircularArcSegment,
    AuthoredLineSegment,
    AuthoredPathSegment,
    AuthoredSegment,
    AuthoredVertex,
    CapsuleOperand,
    DiskOperand,
    PlanarPath as AnalyticPlanarPath,
    PlanarRegionOperand,
    PlanarRelationshipQuery,
    PlanarRing as AnalyticPlanarRing,
    PointNm as AnalyticPointNm,
    StageOperation,
    SweptPathOperand,
)
from ._ipc_client import (
    GeometerIpcClient as GeometerClient,
    GeometerIpcError,
    GeometerIpcProcessError,
    GeometerIpcProtocolError,
    GeometerIpcTimeoutError,
    GeometerOperationError,
)
from ._types import (
    HlrOptions,
    HlrProjectionResult,
    ModelBoundsResult,
    PlanarBatchSolveJob,
    PlanarBatchSolveResult,
    PlanarPoint,
    PlanarRegion,
    PlanarRing,
    ProjectionView,
    Version,
)

__all__ = [
    "AnalyticPlanarBooleanBatchRequestA0",
    "AnalyticPlanarBooleanBatchResultA0",
    "AnalyticPlanarBooleanJob",
    "AnalyticPlanarBooleanStage",
    "AnalyticPlanarOperand",
    "AnalyticPlanarPath",
    "AnalyticPlanarRing",
    "AnalyticPointNm",
    "AnalyticPacketError",
    "AnnulusOperand",
    "ArcDirection",
    "AuthoredCircularArcByRadiusSegment",
    "AuthoredCircularArcSegment",
    "AuthoredLineSegment",
    "AuthoredPathSegment",
    "AuthoredSegment",
    "AuthoredVertex",
    "CapsuleOperand",
    "DiskOperand",
    "GeometerClient",
    "GeometerError",
    "GeometerIpcError",
    "GeometerIpcProcessError",
    "GeometerIpcProtocolError",
    "GeometerIpcTimeoutError",
    "GeometerOperationError",
    "GeometerBatchConfig",
    "GeometerBatchResult",
    "GeometerBatchRunner",
    "HlrOptions",
    "HlrProjectionResult",
    "ModelBoundsResult",
    "PlanarBatchSolveJob",
    "PlanarBatchSolveResult",
    "PlanarRegionOperand",
    "PlanarRelationshipQuery",
    "PlanarPoint",
    "PlanarRegion",
    "PlanarRing",
    "ProjectionView",
    "StageOperation",
    "SweptPathOperand",
    "Version",
    "executable_path",
    "hlr_projection_json",
    "model_bounds",
    "model_bounds_json",
    "model_hlr_projection_json",
    "model_to_glb",
    "planar_batch_solve",
    "planar_batch_solve_json",
    "planar_step",
    "project_model_hlr",
    "project_step_hlr",
    "run_batch",
    "step_to_glb",
    "version",
    "write_planar_step",
    "decode_analytic_planar_boolean_batch_result_a0_packet",
    "encode_analytic_planar_boolean_batch_request_a0_packet",
]
