"""Write the persisted dist/ artifact manifest."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DIST_DIR = ROOT / "dist"
README = DIST_DIR / "README.md"


ROWS = [
    (
        "`native/<platform>/geometer(.exe)`",
        "Native CLI",
        "Command-line STEP/HLR/planar tool for source checkouts. Current platform names use `windows-x64`, `linux-x64`, `macos-x64`, and `macos-arm64`.",
    ),
    (
        "`native/<platform>/geometer.lib`, `native/<platform>/libgeometer.a`",
        "Native static library",
        "Persisted native library artifacts for downstream source checkouts.",
    ),
    (
        "`wasm/browser/geometer.js`, `wasm/browser/geometer.wasm`",
        "Full browser/Web Worker integration WASM",
        "Official application integration build. Exports `createGeometerModule` and the full C ABI, including OCCT-backed STEP-to-GLB, HLR, and planar byte APIs.",
    ),
    (
        "`wasm/node-test/geometer-node-test.js`, `wasm/node-test/geometer-node-test.wasm`",
        "Node CLI parity/test WASM",
        "Node-only command-line build with real filesystem access. Use for tests and diagnostics, not browser integration.",
    ),
    (
        "`wasm/planar-browser/geometer-planar-browser.js`, `wasm/planar-browser/geometer-planar-browser.wasm`",
        "Planar-only browser/Web Worker optimization",
        "Smaller optional build exporting `createGeometerPlanarModule` and planar byte APIs only. Use when STEP/OCCT operations are not needed and startup, download size, or worker memory matter.",
    ),
    (
        "`geometer.exe`, `geometer.js`, etc. at dist root",
        "Compatibility aliases",
        "Flat copies are retained for existing source checkouts while consumers migrate to the grouped layout.",
    ),
]


def main() -> None:
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Geometer Dist Artifacts",
        "",
        "This directory contains persisted runtime artifacts for source checkouts.",
        "It is generated by `scripts/write_dist_manifest.py`; update it after build-output naming changes.",
        "",
        "Canonical artifacts are grouped by runtime target:",
        "",
        "- `native/<platform>/` for native CLI/static-library artifacts.",
        "- `wasm/browser/` for the full browser integration target.",
        "- `wasm/node-test/` for the Node CLI parity/test target.",
        "- `wasm/planar-browser/` for the smaller planar-only browser target.",
        "",
        "`wasm/browser/geometer.js` / `geometer.wasm` is the official browser integration target.",
        "`wasm/planar-browser/geometer-planar-browser.js` / `geometer-planar-browser.wasm` is retained as",
        "a smaller planar-only optimization. The full target also exports the planar",
        "byte APIs, so consumers can choose simplicity or lower startup/memory cost.",
        "Flat files at the root of `dist/` are compatibility aliases for existing",
        "tools and may be removed after downstream consumers migrate.",
        "",
        "| Artifact | Role | Notes |",
        "|---|---|---|",
    ]
    for artifact, role, notes in ROWS:
        lines.append(f"| {artifact} | {role} | {notes} |")
    lines.extend(
        [
            "",
            "Generated build state is not persisted here. Keep `.deps/`, `build/`, and `build-wasm/` out of Git.",
            "",
        ]
    )
    README.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
