#include "cli_usage.h"

#include <cstdio>

void print_usage()
{
    std::fprintf(stderr,
                 "Usage: geometer <command> [options]\n"
                 "\n"
                 "Commands:\n"
                 "  --version                               Print version information\n"
                 "  model-bounds <input.step> <output.json> Emit source model bounds JSON\n"
                 "  model-to-glb <input.step> <output.glb>   Convert source model to GLB\n"
                 "  model-project-hlr <input.step> <output.json>\n"
                 "                                               Emit source model HLR JSON\n"
                 "  model-project-svg <input.step> <output.svg>\n"
                 "                                               Emit source model HLR SVG\n"
                 "  mesh-project-hlr <input.mesh> <output.json>  Emit indexed-mesh Fast HLR JSON\n"
                 "  step-to-glb <input.step> <output.glb>       Convert STEP to GLB\n"
                 "  step-project-hlr <input.step> <output.json> Emit HLR projection JSON\n"
                 "  step-project-svg <input.step> <output.svg>  Emit HLR projection SVG\n"
                 "  planar-step <request.json> <output.step>    Emit exact planar STEP\n"
                 "  run <request.json> <response.json>          Run JSON batch jobs\n"
                 "  init-request <request.json> --step <path>   Write a starter JSON request\n"
                 "  planar-batch-solve <request.bin> <response.bin>\n"
                 "                                               Solve packed planar batch bytes\n"
#ifndef __EMSCRIPTEN__
                 "  serve --stdio                                Serve framed executable IPC A0\n"
#endif
                 "\n"
                 "Options:\n"
                 "  --deflection <value>   Absolute linear deflection (forces absolute mode)\n"
                 "  --deflection-mode <absolute|bbox-relative>  (default: bbox-relative)\n"
                 "  --deflection-coefficient <value>            (default: 0.004)\n"
                 "  --angular <value>      Angular deflection (default: 0.5)\n"
                 "  --projection-algorithm <poly|exact|fast> (default: poly)\n"
                 "  --outline-algorithm <hlr-close|mesh-shadow|fast-mesh-shadow>\n"
                 "                                               (default: hlr-close)\n"
                 "  --format <step>        Source model format (only step is supported)\n"
                 "  --view <id>            SVG view id (default: top)\n"
                 "  --mode <outline|detail|bbox> SVG mode (default: outline)\n"
                 "  --curve-mode <native-arcs|polyline>\n"
                 "  --samples <count>      Curve polyline samples (default: 24)\n"
                 "  --round-digits <count> Projection rounding digits (default: 3)\n"
                 "  --options <path>       Canonical JSON options for mesh-project-hlr\n"
                 "  --operation <name>     init-request operation\n"
                 "  --output <path>        init-request output path\n"
                 "  --repeat <count>       Planar benchmark repeat count (default: 1)\n"
                 "  --warmup <count>       Planar benchmark warmup count (default: 0)\n"
                 "  --metrics <path>       Write planar benchmark JSON metrics\n"
                 "  --format <binary|json> planar-batch-solve output format\n"
                 "  --return-rings <true|false> alias for --format json\n"
                 "\n"
                 "Fast HLR canonical JSON options (`run` request fast object):\n"
                 "  include_boundaries, include_creases, include_silhouettes,\n"
                 "  include_hidden, suppress_coplanar_seams, crease_angle_rad,\n"
                 "  weld_tolerance, projected_tolerance, depth_tolerance,\n"
                 "  coplanar_seam_angle_rad, coplanar_seam_depth_tolerance,\n"
                 "  coplanar_seam_lateral_tolerance, and bounded limits.\n"
                 "  Angles are radians; geometric tolerances use model units.\n");
}
